package kg.peaksoft.ebookm1.api.payloads.dto.enums;

public enum Genre {

    DETECTIVE,ACTION_ADVENTURE, MYSTERY, HORROR,THRILLER_SUSPENSE,
    HISTORICAL_FICTION, ROMANCE, YOUNG_ADULT,BIOGRAPHY, FOOD_DRINK,
    ART_PHOTOGRAPHY, HISTORY, TRAVEL, TRUE_CRIME,HUMOR, ESSAYS,
    PARENTING_FAMILIES, SCIENCE_TECHNOLOGY, CHILDREN_S
}